### ISSUE TITLE
File is already in use by other mod but that's not true

### ISSUE THREAD

**Issue by xDevi69** [sindre-gangeskar/shadps4-alchemist#1]
Version: 0.0.1

How to reproduce: 

1)Download fps boost mod from Nexus: https://www.nexusmods.com/bloodborne/mods/27

2)Try to enable the mod in Alchemist on a fully clean extracted bloodborne PKG and It will fail. 

3)the mod Will be disabled but now a bunch of files starting with an un underscore will be created, even if the mod fails to enable. I have to restore the files manually or use a powershell script to regain the original file structure.

**Comment by sindre-gangeskar** [comment]
Thanks for telling me about this! 
I'll look into this!

**Comment by sindre-gangeskar** [comment]
I think I found the issue. The FPS mod has a directory called "MapStudio" but in the game's directory, it's "mapstudio". 
I'm pretty sure it's causing an issue since it can't find "MapStudio" as in.. case-sensitive. 

I'm going to see if forcing all filenames to lowercase will help.  

Scratch that, that isn't the issue. Still looking

**Comment by sindre-gangeskar** [comment]
Okay, I may've figured it out and fixed it. Hopefully it stays fixed

> Version: 0.0.1
> 
> How to reproduce:
> 
> 1)Download fps boost mod from Nexus: https://www.nexusmods.com/bloodborne/mods/27
> 
> 2)Try to enable the mod in Alchemist on a fully clean extracted bloodborne PKG and It will fail.
> 
> 3)the mod Will be disabled but now a bunch of files starting with an un underscore will be created, even if the mod fails to enable. I have to restore the files manually or use a powershell script to regain the original file structure.

I have fixed this issue now, I think.. 😓 
Please see if the issue is still there. (Please clean your game files first before attempting it)

There should be a version update for you once you launch shadPS4 Alchemist if you have v0.0.1 or v0.0.2

**Comment by vesper8** [comment]
Do other mods activate correctly? Are your games on a NTFS formatted drive? Alchemist doesn't currently support exFAT or FAT32 drives.
